### ISSUE TITLE
[Feature] 유저 검색 모달창

### ISSUE THREAD

**Issue by boltang2** [codestates/mohazi-client#13]
### TODO
1. [x] 주어진 레이아웃 형태로 랜더링 구현
2. [x] 친구 추가시 update detail page에 반영
3. [x] close 버튼 클릭시 창 닫기
4. [x] 배경 클릭시 창 닫기
4. [x] 키 다운 이벤트마다 검색기능 구현
