### ISSUE TITLE
[Feature] 추천 리스트 / 장소 선택 기능

### ISSUE THREAD

**Issue by franhhk** [codestates/mohazi-client#28]
### TODO
1. [x] 항목별 드랍다운 버튼 생성 
2. [x] 사용자가 지도상에 클릭한 위치 기반으로 해당 항목의 추천리스트 출력
3. [x] 스크롤 가능
4. [x]  원하는 장소 클릭시 선택한 항목에 추가
