### ISSUE TITLE
[Feature] 프로필/카드 사진 관리

### ISSUE THREAD

**Issue by franhhk** [codestates/mohazi-client#36]
### TODO
1. [x] 카드 사진 미등록 시 기본 사진 보여주기
2. [x] 프로필 사진 미등록 시 기본 사진 보여주기
3. [x] 카드 사진 등록시 맨 처음 사진으로 보여주기

## Mypage
1. [x] dailyCards
2. [x] Profile

## ShowDetail Page
1. [x] Friends Icon
2. [x] Saved Photos

## UpdateDetail Page
1. [x] Friends Icon
2. [x] Saved Photos
