### ISSUE TITLE
[Fix] 카카오맵 마커

### ISSUE THREAD

**Issue by franhhk** [codestates/mohazi-client#51]
### TODO
1. [x] 사용자 위치 표시 마커와 장소 표시 마커 종류 구분하기
2. [x] 마커 infowindow 이벤트: click -> mouseover
3. [x] 마우스를 올리지 않았을 때 infowindow 닫기
